# Generated by Django 3.2.4 on 2021-07-16 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='user_business_line',
            field=models.CharField(default='NA', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='user_region',
            field=models.CharField(default='NA', max_length=20, null=True),
        ),
    ]
