# Generated by Django 3.2.4 on 2021-07-13 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FilterData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filter_ID', models.IntegerField()),
                ('filter_name', models.CharField(max_length=50)),
                ('filter_component', models.CharField(max_length=50)),
                ('filter_description', models.CharField(max_length=20)),
                ('region', models.CharField(max_length=20)),
                ('business_line', models.CharField(max_length=20)),
                ('legal_entity', models.CharField(max_length=20)),
                ('profit_center', models.CharField(max_length=20)),
                ('book_name', models.CharField(max_length=20)),
                ('cob_dt', models.DateField()),
            ],
        ),
    ]
