# Generated by Django 3.2.4 on 2021-07-13 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Filters', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filterdata',
            name='cob_dt',
            field=models.DateField(null=True),
        ),
    ]
