# Generated by Django 3.2.5 on 2021-07-13 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exceptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exceptiontype',
            name='exception_BusinessLine',
            field=models.CharField(default='anonymous', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exceptiontype',
            name='exception_COBDT',
            field=models.DateField(default='2000-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exceptiontype',
            name='exception_LegalEntity',
            field=models.CharField(default='anonymous', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exceptiontype',
            name='exception_ProfitCenter',
            field=models.CharField(default='anonymous', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exceptiontype',
            name='exception_Region',
            field=models.CharField(default='anonymous', max_length=50),
            preserve_default=False,
        ),
    ]
