# Generated by Django 3.0.1 on 2021-07-25 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FastData', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flaginserttable',
            name='isException',
            field=models.BooleanField(default=True),
        ),
    ]
