# Generated by Django 3.0.1 on 2021-07-14 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountingData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Data_ID', models.IntegerField()),
                ('Data_name', models.CharField(default='', max_length=50, null=True)),
                ('Data_component', models.CharField(default='', max_length=20, null=True)),
                ('Data_level', models.CharField(default='', max_length=20, null=True)),
                ('Data_description', models.CharField(default='', max_length=50, null=True)),
                ('Data_COBDT', models.DateField(default='2000-01-01')),
                ('Data_LegalEntity', models.CharField(default='', max_length=50, null=True)),
                ('Data_ProfitCenter', models.CharField(default='', max_length=50, null=True)),
                ('Data_BusinessLine', models.CharField(default='', max_length=50, null=True)),
                ('Data_Region', models.CharField(default='', max_length=50, null=True)),
            ],
        ),
    ]
