# Generated by Django 3.0.1 on 2021-07-14 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounting', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accountingdata',
            old_name='Data_component',
            new_name='Exceptiom_level',
        ),
        migrations.RenameField(
            model_name='accountingdata',
            old_name='Data_BusinessLine',
            new_name='Exception_BusinessLine',
        ),
        migrations.RenameField(
            model_name='accountingdata',
            old_name='Data_COBDT',
            new_name='Exception_COBDT',
        ),
        migrations.RenameField(
            model_name='accountingdata',
            old_name='Data_ID',
            new_name='Exception_ID',
        ),
        migrations.RenameField(
            model_name='accountingdata',
            old_name='Data_LegalEntity',
            new_name='Exception_LegalEntity',
        ),
        migrations.RenameField(
            model_name='accountingdata',
            old_name='Data_ProfitCenter',
            new_name='Exception_ProfitCenter',
        ),
        migrations.RenameField(
            model_name='accountingdata',
            old_name='Data_Region',
            new_name='Exception_Region',
        ),
        migrations.RenameField(
            model_name='accountingdata',
            old_name='Data_level',
            new_name='Exception_component',
        ),
        migrations.RenameField(
            model_name='accountingdata',
            old_name='Data_description',
            new_name='Exception_description',
        ),
        migrations.RenameField(
            model_name='accountingdata',
            old_name='Data_name',
            new_name='Exception_name',
        ),
    ]
