# Generated by Django 3.2.4 on 2021-07-16 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounting', '0003_auto_20210716_0959'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accountingdata',
            old_name='exceptiom_level',
            new_name='exception_level',
        ),
    ]
